#!/usr/bin/env bash
set -euo pipefail

RAAS_KEY_FILE="/etc/raas/pki/.raas.key"
RAAS_PERSIST_KEY_PATH="${RAAS_PERSIST_KEY_PATH:-/var/lib/raas/.raas.key}"
RAAS_PERSIST_CUSTOMER_ID_PATH="${RAAS_PERSIST_CUSTOMER_ID_PATH:-/etc/raas/customer_id}"

# Keep runtime setup focused on nested writable paths. The image already owns
# the top-level RaaS directories, while Kubernetes and Compose replace those
# roots with mounted volumes at runtime.
mkdir -p \
  /etc/raas/pki \
  /etc/pki/raas/certs \
  "$(dirname "${RAAS_PERSIST_KEY_PATH}")" \
  "$(dirname "${RAAS_PERSIST_CUSTOMER_ID_PATH}")"

if [ ! -s /etc/raas/raas ]; then
  echo "[entrypoint] Seeding /etc/raas/raas from /bootstrap/raas"
  cp /bootstrap/raas /etc/raas/raas
fi

# Keep the template generic in the image and stamp in service names at runtime
# so the same image can be reused in the lab and later in Kubernetes.
sed -i "s#@@DB_HOST@@#${RAAS_DB_HOST:-ssc-postgres}#g" /etc/raas/raas
sed -i "s#@@REDIS_HOST@@#${RAAS_REDIS_HOST:-ssc-redis}#g" /etc/raas/raas
sed -i "s#@@REDIS_PORT@@#${RAAS_REDIS_PORT:-6379}#g" /etc/raas/raas

TLS_CRT="/etc/pki/raas/certs/localhost.crt"
TLS_KEY="/etc/pki/raas/certs/localhost.key"
TLS_CN="${RAAS_TLS_CN:-ssc-raas}"

generate_uuid() {
  if [ -r /proc/sys/kernel/random/uuid ]; then
    cat /proc/sys/kernel/random/uuid
    return 0
  fi

  /opt/saltstack/raas/bin/python3 - <<'PY'
import uuid
print(uuid.uuid4())
PY
}

normalize_uuid() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

# Broadcom's customer_id is the namespace boundary inside the RaaS database.
# Generate it once when the operator has not supplied one, and then persist it
# so separate deployments do not all stamp the same identifier into their DB.
if [ -n "${RAAS_CUSTOMER_ID:-}" ]; then
  customer_id="$(normalize_uuid "${RAAS_CUSTOMER_ID}")"
elif [ -s "${RAAS_PERSIST_CUSTOMER_ID_PATH}" ]; then
  customer_id="$(normalize_uuid "$(tr -d '\r\n' < "${RAAS_PERSIST_CUSTOMER_ID_PATH}")")"
else
  customer_id="$(generate_uuid)"
  echo "[entrypoint] Generated RaaS customer_id ${customer_id}"
fi

if [ ! -s "${RAAS_PERSIST_CUSTOMER_ID_PATH}" ] || [ "$(tr -d '\r\n' < "${RAAS_PERSIST_CUSTOMER_ID_PATH}" 2>/dev/null || true)" != "${customer_id}" ]; then
  echo "${customer_id}" > "${RAAS_PERSIST_CUSTOMER_ID_PATH}"
fi

chmod 600 "${RAAS_PERSIST_CUSTOMER_ID_PATH}" 2>/dev/null || true
sed -i -E "s#^customer_id:.*#customer_id: \"${customer_id}\"#" /etc/raas/raas

# Keep the RaaS encryption key on the persistent data path so a pod restart
# does not invalidate the database it already initialized. The live key still
# sits in /etc/raas/pki where the application expects it.
if [ -s "${RAAS_PERSIST_KEY_PATH}" ] && [ ! -s "${RAAS_KEY_FILE}" ]; then
  echo "[entrypoint] Restoring persisted RaaS encryption key"
  cp "${RAAS_PERSIST_KEY_PATH}" "${RAAS_KEY_FILE}"
fi

chmod 700 /etc/raas/pki || true
chmod 600 "${RAAS_KEY_FILE}" 2>/dev/null || true

# Broadcom's appliance model expects RaaS to terminate TLS itself. If the lab
# operator did not mount a cert/key pair, generate a self-signed pair so the
# service still comes up on HTTPS without a manual prep step.
if [ ! -s "${TLS_CRT}" ] || [ ! -s "${TLS_KEY}" ]; then
  echo "[entrypoint] Generating self-signed TLS certificate for ${TLS_CN}"
  openssl req -x509 -nodes -newkey rsa:4096 \
    -keyout "${TLS_KEY}" \
    -out "${TLS_CRT}" \
    -days "${RAAS_TLS_DAYS:-825}" \
    -subj "/CN=${TLS_CN}" \
    -addext "subjectAltName=DNS:${TLS_CN},DNS:localhost,IP:127.0.0.1"
fi

chmod 600 "${TLS_KEY}" || true
chmod 644 "${TLS_CRT}" || true

# The secconf file stores database and Redis credentials in the format expected
# by `raas`. Create it once and then leave it alone so restarts are idempotent.
if [ ! -f /etc/raas/raas.secconf ]; then
  echo "[entrypoint] Creating /etc/raas/raas.secconf with raas save_creds"
  /opt/saltstack/raas/bin/raas -c /etc/raas save_creds \
    "postgres={\"username\":\"${RAAS_DB_USER:-raas}\",\"password\":\"${RAAS_DB_PASS:-raaspass}\"}" \
    "redis={\"password\":\"${RAAS_REDIS_PASS:-}\"}"
fi

chmod 600 /etc/raas/raas.secconf || true

# The crypt key is generated by RaaS during startup, not by this entrypoint.
# Sync it back to persistent storage in the background once it appears so later
# restarts reuse the same key material.
"$@" &
raas_pid=$!

(
  for _ in $(seq 1 "${RAAS_KEY_SYNC_ATTEMPTS:-180}"); do
    if [ -s "${RAAS_KEY_FILE}" ]; then
      if [ ! -s "${RAAS_PERSIST_KEY_PATH}" ]; then
        cp "${RAAS_KEY_FILE}" "${RAAS_PERSIST_KEY_PATH}"
        chmod 600 "${RAAS_PERSIST_KEY_PATH}" || true
        echo "[entrypoint] Persisted RaaS encryption key to ${RAAS_PERSIST_KEY_PATH}"
      fi
      exit 0
    fi
    sleep 2
  done
  echo "[entrypoint] Timed out waiting to persist the RaaS encryption key" >&2
) &
sync_pid=$!

wait "${raas_pid}"
raas_status=$?
wait "${sync_pid}" || true
exit "${raas_status}"
